WINDOW_WIDTH = 800

WINDOW_HEIGHT = 600

CHARACTER_WIDTH = 20

CHARACTER_HEIGHT = 20

CHARACTER_COLOR = (255,255,0)

BG_COLOR = (0,0,20)

FPS = 60

MOVEMENT = 5 

PATH_IMAGE = "assets\images\characters\player\FA_TEDDY_Walk_"

PATH_WEAPON = "assets\images\weapons\weapon_1.png"

SCALE_CHARACTER = 54